# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_incomplete_blocks <- function(mat) {
    .Call('_acre_find_incomplete_blocks', PACKAGE = 'acre', mat)
}

blockify <- function(block, reqss) {
    .Call('_acre_blockify', PACKAGE = 'acre', block, reqss)
}

detection_dists <- function(trap_dists, traps) {
    .Call('_acre_detection_dists', PACKAGE = 'acre', trap_dists, traps)
}

detection_timediffs <- function(times, traps) {
    .Call('_acre_detection_timediffs', PACKAGE = 'acre', times, traps)
}

min_skip_matrix <- function(skip, allocated) {
    .Call('_acre_min_skip_matrix', PACKAGE = 'acre', skip, allocated)
}

distances <- function(a, b) {
    .Call('_acre_distances', PACKAGE = 'acre', a, b)
}

bearings <- function(a, b) {
    .Call('_acre_bearings', PACKAGE = 'acre', a, b)
}

make_toa_ssq <- function(capt, dists, sound_speed) {
    .Call('_acre_make_toa_ssq', PACKAGE = 'acre', capt, dists, sound_speed)
}

find_local <- function(capt, dists, buffer) {
    .Call('_acre_find_local', PACKAGE = 'acre', capt, dists, buffer)
}

squarify <- function(mask, D_mask) {
    .Call('_acre_squarify', PACKAGE = 'acre', mask, D_mask)
}

